### ISSUE TITLE
Połączenie użytkownika z politykiem w bazie danych

### ISSUE THREAD

**Issue by lord-vader123** [lord-vader123/polityczna-strona#24]
W tabeli polityk można by dodać klucz obcy odwołujący się do użytkownika. Dzięki temu na stronie można umieścić informację kto dodał jakiego polityka. Uważam to za pomysł godny rozważenia i wykonania Panie @Real-Morbius

**Comment by lord-vader123** [comment]
W sumie to pole login w userze powinno być unique

**Comment by Real-Morbius** [comment]
Zrobione wariacie
